services:
  db:
      container_name: mariadb
      image: mariadb:12.0.1-noble-rc
      expose:
        - "3306"
      environment:
        MYSQL_DATABASE: universidad
        MYSQL_USER: alumno
        MYSQL_PASSWORD: alumno1
        MYSQL_ROOT_PASSWORD: pass
      volumes:
        - ./databases:/docker-entrypoint-initdb.d/
      networks:
        - landb

networks:
  landb:
    driver: bridge